name: CI
on:
  push:
    branches:
      - main
env:
  PACKAGE_NAME: jsonpath-notebook-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}.vsix
jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'
  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: yarn install
      - run: yarn package -o "${{ env.PACKAGE_NAME }}"
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./${{ env.PACKAGE_NAME }}